### ISSUE TITLE
[UI/UX] Network user clicks an edge

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#10]
The network view displays edges between genes that have high correlation across the entire model. When an edge is clicked, we'd like to display more detailed information about that specific edge.

Actual interface:
![screenshot from 2016-09-28 09-45-04](https://cloud.githubusercontent.com/assets/542643/18915839/5c2158c0-8560-11e6-8c00-e0e92cf81f9e.png)

My drawing of the interface above:
![img_20160928_092545-edgeclick](https://cloud.githubusercontent.com/assets/542643/18916017/eb484e1e-8560-11e6-9469-6ba6a52c46b7.jpg)

Upon click, a small box appears. This box provides the correlation of the two genes over the ADAGE model at the top. In addition to this information, it provides a list of all nodes that have both of these genes as 'high-weight' genes.

![img_20160928_092545-tooltip](https://cloud.githubusercontent.com/assets/542643/18916095/387a5f38-8561-11e6-9c97-a5ef6c89dae7.jpg)

These nodes are clickable links. Upon a click, this takes the user to a node detail page. The node detail page provides information pertinent to the node. I'll file another issue for this.

**Comment by cgreene** [comment]
#11 is now a stub of a 'node view page' description

**Comment by cgreene** [comment]
@georgiadoing suggested that the shared nodes could also include a count of genes that each node has as high weight.

**Comment by dongbohu** [comment]
I checked `model.py` and `api.py` in Django. Right now this query is not supported in `NodeResource` or `EdgeResource` class. `NodeResource` class seems to be a good place to implement this functionality. We can add a new query such as `heavy_genes=123, 456` into this class.
