### ISSUE TITLE
Color genes by expression fold change in the gene-gene network

### ISSUE THREAD

**Issue by tj8901nm** [greenelab/adage-server#101]
1. After users define two groups of samples in the sample page, the gene expression values of these samples should be retrieved. 
2. Then each gene's expression fold change between group1 and group2 are calculated. The fold change is defined as the gene's `mean expression value of samples in group2 - mean expression value of samples in group1`.
3. Next users use their interested signatures to build a gene-gene network for the above samples. In the network, the color of the gene should reflect the gene's expression fold change between two sample group. 

Note that genes should only be colored by fold change if the network is built to analyze two groups of samples. If users directly go to the network page, the network is not specifically linked to any dataset and genes should not be colored.

**Comment by dongbohu** [comment]
Thanks. One question: When you calculate the color in step 3, I suppose you are using a linear legend bar similar to the one in the current gene-gene network. What are the colors on the left-most and right-most sides?

**Comment by tj8901nm** [comment]
I pinned `ArrayExpress example.html` in our slack channel. Please refer to the gene colors used in it. Red is highest positive fold change and blue is highest negative fold change.

**Comment by dongbohu** [comment]
@tj8901nm: When you use the fold change to set each gene's color, are you using the absolute value of the fold change or the real value? Thanks.

**Comment by dongbohu** [comment]
@tj8901nm: Is it possible that in a gene-gene network, some genes have an expression value but some genes don't have it at all? If it is possible, do you color the genes without the expression value as "0" or not color any genes at all? Thanks.

**Comment by tj8901nm** [comment]
I haven't encountered a situation like this but I can imagine it happens when an input dataset is not measured on the same platform as the compendium and thus some genes were not available in the input dataset. I think I'd prefer to color such genes with a unique color in order to differentiate them from zero expression changes.

**Comment by dongbohu** [comment]
Got it. Thanks.
