### ISSUE TITLE
Hard coded MLModel in analysis.js

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#115]
In `app/analyze/analysis/analysis.js`, lines 55-56:
```
    // FIXME MLModel is hard-coded until heatmap has a selector added
    $state.go('volcano', {'mlmodel': 1});
```
Although Matt has labelled it as a **FIXME**, I want to emphasize the importance of this fix, because on my desktop, the default MLModel ID is 4 (for historical reasons), and this hard coded ID prevents me from testing the link to volcano plot.

**Comment by mhuyck** [comment]
Fix for this is in, but I need to do something with the MLModel selector component to make it properly useable. Almost there!
