### ISSUE TITLE
Create and implement a front-end selector for ParticipationType (sub-issue of Issue #58)

### ISSUE THREAD

**Issue by rzelayafavila** [greenelab/adage-server#119]
Sub-issue of issue #58 

This front-end selector would be tied to whatever ParticipationTypes are added to the backend (issue #118 ).

As per the comments on #58, we should:
*Change the High-weight genes section of the Node page so that it will show the participation type. We may need new widget on web UI to allow users to select participation type that they are interested in.

**Comment by dongbohu** [comment]
Being addressed in PR #160.

**Comment by rzelayafavila** [comment]
Resolved with merging of PR #160
