### ISSUE TITLE
Generalize enrichment tests for whatever ParticipationType is selected (sub-issue of Issue #58)

### ISSUE THREAD

**Issue by rzelayafavila** [greenelab/adage-server#120]
Sub-issue of Issue #58

**Comment by dongbohu** [comment]
This issue seems to be related to #160.

**Comment by rzelayafavila** [comment]
This was also resolved with merging of PR #160, since the "Enriched gene sets" table now updates itself every time the user selects a different ParticipationType (basing itself on whatever the participatory genes are).
