### ISSUE TITLE
Node Page: Hard-coded Organism Name

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#121]
`interface/src/app/node/node.js` line 55:
```
self.organism = 'Pseudomonas aeruginosa';
```

This variable is used by `enrichedGenesets` directive. I wonder whether a widget should be added to allow user to select organisms.

**Comment by rzelayafavila** [comment]
So this should actually come from the MLModel that has already been selected. It is actually connected to some of the changes I am making in the PR I am working on, so I will make sure to fix this!

**Comment by dongbohu** [comment]
Being addressed in PR #160.

**Comment by rzelayafavila** [comment]
Resolved with merging of PR #160

**Comment by rzelayafavila** [comment]
Resolved with merging of PR #160
