### ISSUE TITLE
Can we make the search ignore capitalization

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#123]

**Comment by dongbohu** [comment]
You mean the gene search?

**Comment by cgreene** [comment]
I think this is @mhuyck's search box. There were some issues finding the desired experiment.

**Comment by mhuyck** [comment]
Right, this is the search that looks up samples and experiments to add to the sample bin. It is case sensitive in some scenarios now and we'd like it to not be. I believe the example Deb used was something like `DnaQ` and `dnaQ`. The first one (capitalized) refers to the protein and the second is the gene. A search of text should find either one.

**Comment by mhuyck** [comment]
This will involve tweaking the elasticsearch indexing parameters and re-indexing a few times to get it right.

**Comment by cgreene** [comment]
plus writing tests with small cases to make sure it works and reduce the number of tests where you have to rebuild the full index :)

**Comment by mhuyck** [comment]
The case of the initial letter wasn't ever supposed to matter, so I'm noting that this is a bug. Changes in internal case (the `Q` in the `dnaQ` example above) do make a difference. A previous bug fix made an adjustment for an example that Jie couldn't find. I'm assigning this to myself to ensure we get the subtlety of both cases right.

**Comment by mhuyck** [comment]
Okay, I think I've figured this out... the search *is* case insensitive already with the exception of certain cases where there are *internal* changes in case.

Here is an example of what's happening now:

1. searching on either `mexR` or `MexR` will return two legitimate hits (the same ones) in each case
2. searching on `MEXR` or `mexr` will not return either of those hits

Case 1 is correct behavior and should not change. Case 2 gives the false impression that the text is missing `mexR`, which is wrong and should be corrected.

This unexpected behavior appears to be related to the Elasticsearch `word_delimiter` token filter we added to resolve a different bug. There appears to be a parameter on that filter that I can tweak to give us what we want.

**Comment by mhuyck** [comment]
Okay, I was able to get the expected results by changing the `split_on_case_change` parameter from its default of `true` to `false` and re-indexing.

I looked into writing some tests (as suggested by @cgreene) and we currently have *none* that target our search indexes, so that will require adding a bit of test infrastructure. I assume that Tribe has some tests that exercise the search index. Any tips on where to look for that, @rzelayafavila?

**Comment by mhuyck** [comment]
I've found `tribe/genesets/tests.py` over at https://bitbucket.org/greenelab/tribe/src/53ef3f6c7f9a9911055c15f4b22e4016d10984e6/genesets/tests.py?at=default&fileviewer=file-view-default so I'm looking into implementing that setup for `adage-server`.

**Comment by rzelayafavila** [comment]
Hi @mhuyck - yep, the genesets tests include tests for search indexes. Also, there are a couple of tests that might be useful in the BuildingGeneIndexTestCase in ``django-genes``: https://bitbucket.org/greenelab/django-genes/src/52dd0635b80604be8ac616399c7101a480020fe5/genes/tests.py?at=default&fileviewer=file-view-default
