### ISSUE TITLE
Network force simulation should stop

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#124]
After some pre-defined interval, the nodes should stop moving. When a user moves a node, the force simulation should not be re-run.

**Comment by dongbohu** [comment]
This feature is not available in `d3.network`. Need to read `d3` doc to figure out the best way to implement it.

**Comment by cgreene** [comment]
It is implemented in GIANT - I thought that used d3.network. If not @aaronkw should know how to do this.
http://giant.princeton.edu/contexts/integration/?id=149&gene=672

**Comment by aaronkw** [comment]
Adding this to the force 'tick' function should do the trick:
```javascript
            // After layout, fix all nodes in place
            if ( e.alpha * .99 < .005 && e.alpha > 0 ) {
              selection.selectAll("circle.gene").each(function(g){
                  g.fixed = true;
              });
            }
```

**Comment by dongbohu** [comment]
Thanks @aaronkw! I will try that.

**Comment by dongbohu** [comment]
Fixed by following Aaron's suggestion. `d3.network` code modified in:
https://github.com/dongbohu/d3-network
