### ISSUE TITLE
heatmap bug

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#125]
Heatmap disappears in some situation E-GEOD-4026

**Comment by cgreene** [comment]
In addition to fixing the database, we probably need to make it a bit more robust to "skip" over bad samples.

**Comment by mhuyck** [comment]
Looking into this... I think the database is fine, but something isn't handling missing data well. I'm on it this week.

**Comment by mhuyck** [comment]
The sample named `GSE4026GSM92187` is missing what we call an "ML Data Source," in this case a `.cel` file. I know there are cases where this is expected (from prior discussion with @tj8901nm), so our system needs to handle this case more gracefully.

**Comment by mhuyck** [comment]
Obviously this sample is not part of the MLModel because missing data are (by definition) not included in the compendium used to build ADAGE models.

**Comment by mhuyck** [comment]
Temporary workaround: deleting that sample allows the heatmap to draw.

When it does draw, the large number of samples in this experiment push the vega layout beyond the limited space of its original design. Translation: the heatmap is ugly with this many samples. That will have to be addressed separately.

**Comment by mhuyck** [comment]
Based upon the experiment's page on ArrayExpress, one sample (corresponding to what is triggering this error) is missing raw data. See:

> http://www.ebi.ac.uk/arrayexpress/experiments/E-GEOD-4026/samples/

the second to last sample (source name: "GSE4026GSM92187", hybridization name: "PAOR3 replicate 1 od 0.8") is missing a link to the corresponding raw data.

So the missing data are truly missing from the source, and this is not an error downloading (as I suspected). There may well be reasons to pick out samples from this experiment but ignore this sample, so I am proceeding to add some better error checking so this doesn't break the page for us.
