### ISSUE TITLE
experiments with the highest range should be hoverable

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#130]

**Comment by cgreene** [comment]
Not a dropdown/activity list - hover should give sample annotations.

**Comment by dongbohu** [comment]
After discussion with @casey, we decide to get rid of the "+" sign, and make the vega-lite widget (which shows the activity values) clickable. Clicking it will lead to the page of annotation page of all samples that are related to this experiment.

**Comment by dongbohu** [comment]
Fixed in #156.
