### ISSUE TITLE
it should be specified that node XYZ is the signature

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#133]
Put in "Signature:"

**Comment by dongbohu** [comment]
Can @mhuyck or @cgreene elaborate on exactly what this issue means?

**Comment by cgreene** [comment]
<img width="532" alt="screen shot 2017-05-25 at 3 30 20 pm" src="https://cloud.githubusercontent.com/assets/542643/26467075/1d18ea56-415f-11e7-9e50-4a8dddcd17b1.png">

I would suggest removing the top text "ADAGE: Signature Information" and add "Signature: " before the thing that currently says Node100neg

**Comment by cgreene** [comment]
that is from this page:
http://adage.greenelab.com/#/signature/400

**Comment by dongbohu** [comment]
Got it. That is easy to do. Thanks.

**Comment by dongbohu** [comment]
Being addressed in PR #161.
