### ISSUE TITLE
gene query - is it getting only edges to the query gene or is it getting edges b/w any gene in the queries

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#134]

**Comment by dongbohu** [comment]
It is getting all edges that are related to any of the genes specified in the URL (in other words, a UNION Of all edges related).

**Comment by cgreene** [comment]
Ok - Deb says that what she really wants it to return is:
* Edges to any genes specified in the URL.
* Edges between any genes that appear in the network.

This will let her see which things are small modules of connected genes. I expect this to be the case for most of our users.

**Comment by dongbohu** [comment]
Got it.

**Comment by dongbohu** [comment]
Fixed in PR #194.
