### ISSUE TITLE
Got 'failed to get gene expression value: : 502 Bad gateway.' when analyzing E-MEXP-2593

### ISSUE THREAD

**Issue by mhuyck** [greenelab/adage-server#146]
Report from Deb Hogan:

> I am analyzing E-MEXP-2593 and picked two nodes to look at in the gene network and got this.

> I think that this was Dao's request as well, but it would be nice if you could type in a node in the  Experiments with the Highest Range page.

> One node at a time worked.

**Comment by mhuyck** [comment]
I see the string 'failed to get gene expression value' exactly once in the codebase: `app/gene/network/network.js`, currently line 446.

**Comment by dongbohu** [comment]
`E-MEXP-2593` is the accession of an experiment. What does it mean by `picked two nodes to look at in the gene network`?

**Comment by mhuyck** [comment]
I agree that's confusing. I think she is trying to select nodes in a volcano plot, but can't get the error that way. I will meet with Deb and document the steps to reproduce it.

**Comment by mhuyck** [comment]
Got steps to reproduce via Deb just now.

1. search for `E-MEXP-2593` in the Analyze tab
2. add those samples to the SampleBin (click `+` at right of search result)
3. select the following groups and click "volcano plot":

<img width="1372" alt="screen shot 2017-05-15 at 1 18 24 pm" src="https://cloud.githubusercontent.com/assets/1151166/26070347/4b2ddcca-3972-11e7-9452-02d873c76273.png">

4. select the two signatures above the line (`Node226neg` and `Node297neg`)
5. click "View in Gene Network" and see the error

**Comment by mhuyck** [comment]
Note: the actual error is "Bad Gateway" and appears to arise from the `nginx` layer. When testing directly against the `django-admin runserver` backend, the server happily processes the request and returns the result to the browser.

While we could, in theory, make adjustments to `nginx` settings, this would likely only defer the problem rather than resolve it. The defaults for `nginx` are set up the way they are for good reasons, and other browsers (I am testing with Safari at the moment) will not handle extremely long URIs gracefully.

I mention this here because reproducing the error requires some subtlety.

**Comment by mhuyck** [comment]
Just now got the fix for this working... bug fix should roll out to the server in a few days after code is reviewed and updated.

**Comment by mhuyck** [comment]
Fixed in PR #155
