### ISSUE TITLE
Given a set of genes, it would be nice to identify enriched signatures

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#153]
Deb's lab has people who would like to input a set of genes (maybe as a Tribe geneset?) to identify nodes with significant enrichment. This would be the flip side of functionality in the node table that shows pathways enriched for a node.

**Comment by dongbohu** [comment]
If they just need a list of nodes (with the link to the corresponding node page), we can probably add that functionality into the current gene search web UI:
http://adage.greenelab.com/#/gene_search
All we need to do is add a button like "Show enriched nodes (or signatures)", which when clicked will show the enriched nodes (aka. signatures).

I will talk to Rene when he is back.

**Comment by cgreene** [comment]
@dongbohu : I think this would meet their goals. Thanks!

**Comment by rzelayafavila** [comment]
Changing "nodes" to "signatures" to reflect our current nomenclature.

**Comment by rzelayafavila** [comment]
This is actually much more involved than originally expected, and currently involves many different calls to the backend. Will probably need to create a new api endpoint to retrieve many signatures at once and all of their associated genes (for a given ParticipationType). Kicking this back into next release.

**Comment by dongbohu** [comment]
Rene's WIP PR #343 is supposed to address this issue.

**Comment by dongbohu** [comment]
Implemented in #345.
