### ISSUE TITLE
Adding samples to "shopping cart" is non-obvious

### ISSUE THREAD

**Issue by jaclyn-taroni** [greenelab/adage-server#178]
Unclear how to move from Analyze search step to adding samples to visualization

**Comment by mhuyck** [comment]
True. Thank you for capturing this. I'm going to tag issue #142 as well. That's an over-arching issue where I'm trying to organize concerns about analysis flow.

**Comment by mhuyck** [comment]
Closed by #200. Further work in this area will continue under #142.
