### ISSUE TITLE
Add documentation about files in `data`

### ISSUE THREAD

**Issue by jaclyn-taroni** [greenelab/adage-server#179]
Need description for files in [`data`](https://github.com/greenelab/adage-server/tree/master/data) for folks who have run ADAGE independently of the server and would like to load files for node interpretation and visualization.

**Comment by mhuyck** [comment]
Great catch. We need a README in there to describe those files.

This is not the full solution, but if you need immediate info from the repository itself, have a look at the `import_data_and_index()` function in https://github.com/greenelab/adage-server/blob/master/fabfile/adage_server.py . This is where those data files are loaded into the database during our automated deployment.

**Comment by rzelayafavila** [comment]
Resolved via https://github.com/greenelab/adage-server/pull/180
