### ISSUE TITLE
UI should indicate the gene-gene network's cutoff value

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#184]
Currently the gene-gene network file that has been loaded into the database has a cutoff value of 0.4, but the slider of correlation values on the web UI has a valid range of [0, 1]. This is misleading. We should set the slider's minimum value at the cutoff value.

This issue is related to #183.

**Comment by dongbohu** [comment]
I am trying to figure out the best way to solve this issue. Obviously we can hard code the cutoff value of 0.4 for now, but it won't work if a user loads another gene-gene network file with different cutoff value. 

How about adding a new field `gene_gene_network_cutoff` in `MLModel` table? The management command that loads the gene-gene network will need another argument which allows users to specify this cutoff value when creating the MLModel record.

**Comment by mhuyck** [comment]
This sounds like a great plan. When you update the management command, please also update the `fabfile/adage_server.py` script that calls it during deployment so that step does not break.

**Comment by dongbohu** [comment]
Fixed in PR #201.
