### ISSUE TITLE
Strange result in gene search.

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#198]
Noticed this when playing around with #196 and typing in a few names to try to find some genes to add to the list. I don't _think_ it's directly related, but we seem to have a strange gene named NEWENTRY.

![screenshot from 2017-07-11 16-00-24](https://user-images.githubusercontent.com/542643/28088730-a8e5e100-6654-11e7-84ee-01938fc2fdb1.png)

**Comment by rzelayafavila** [comment]
@cgreene : I would be pretty surprised if it was related to the changes in the front-end, especially since there is a description of it if you hover over it. My suspicion is that it might have been introduced with the gene history file.

**Comment by rzelayafavila** [comment]
P.S. I am in the process of getting a screenshot of that tooltip.

**Comment by cgreene** [comment]
I made a new issue, since I don't think it's related to #196. I suspect it's a bug in our loading code.

**Comment by rzelayafavila** [comment]
![gene_search_adage-server_screenshot](https://user-images.githubusercontent.com/4641983/28089293-8d99d29c-6656-11e7-95a9-4e75406746ee.png)

**Comment by rzelayafavila** [comment]
@cgreene I agree

**Comment by dongbohu** [comment]
This *NEWENTRY* gene is on line 19702 of this file (after unzipped):
ftp://ftp.ncbi.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz
Here is the whole line:
```
9606	192343	NEWENTRY	-	-	-	-	-	Record to support submission of GeneRIFs for a gene not in Gene (human; man).	other	-	-	-	-	20170708
```

**Comment by cgreene** [comment]
That is wild! It's definitely not a gene... I guess they use it as a filler whenever they need to add a gene but the corresponding Entrez entry hasn't been created? Should we add specific code to filter it... or ?

**Comment by dongbohu** [comment]
We probably should filter it out when uploading the gene info file into the database. A quick fix would be to add an extra "if" condition in the code.

**Comment by dongbohu** [comment]
I wonder whether we should also report this fake gene line to whoever maintains this file in NIH.

**Comment by cgreene** [comment]
This would probably be the report form:
https://www.ncbi.nlm.nih.gov/projects/RefSeq/update.cgi

It may be there intentionally to support something... though I wonder if they could filter it before dumping the database to the flat file.

An if statement for now is probably sufficient to save us from this case.

**Comment by cgreene** [comment]
Went ahead and reported upstream. We'll see if they fix it before we add the if statement.

**Comment by cgreene** [comment]
@dongbohu : thanks for fixing! haven't heard back from the database yet :frowning_face:

**Comment by dongbohu** [comment]
Sure. I checked the latest gene info file yesterday and found that the `NEWENTRY` line is still there, so I decided to fix it manually.
