### ISSUE TITLE
Deployment Reminder: reload all data into production server

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#206]
Since a new field (gene-gene network edge cutoff value) has been added in the `MLModel`, please reload all data files into the server when deployment (instead of running migration only).

**Comment by mhuyck** [comment]
Good call, and thanks for the reminder. Since we won't be under time pressure for this deployment, I will do a full deployment to a new database.

**Comment by mhuyck** [comment]
Hah. Just for reference, if we forget to do this, calls to the REST API at `/api/v0/mlmodel/` will come back looking like this:

![screen shot 2017-07-24 at 5 37 09 pm](https://user-images.githubusercontent.com/1151166/28545987-173ac02a-7097-11e7-996b-ebfd04785e61.png)

I did a rebase on my open PR without reloading my database... word of caution to @rzelayafavila, in case you haven't reloaded your MLModel data yet.

**Comment by mhuyck** [comment]
Oh, actually... this is not quite true. I was able to fix my dev instance by just running a `python manage.py migrate`. This puts the default of `0.0` into the new `g2g_edge_cutoff` field, so that wouldn't actually be quite right for the data we have but at least the API won't break as I indicated above.

**Comment by mhuyck** [comment]
Test deployments worked great and put the correct default in when loading data. See http://greenelab.fgtech.com/#/gene_network/?genes=84&mlmodel=1 for an example.

**Comment by rzelayafavila** [comment]
Nice!
