### ISSUE TITLE
Migrate related repos from bitbucket to github

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#211]
(This issue is related to adage-server, so I am using the `August Release` as a to-do list.)

The following three bitbucket repos should be migrated to github:

- [x] tribe: https://bitbucket.org/greenelab/tribe (26 open issues)

- [x] tribe-client: https://bitbucket.org/greenelab/tribe-client (3 open issues)

- [x] annotation-refinery: https://bitbucket.org/greenelab/annotation-refinery (3 open issues)

In each repo: 
- Change the **url** from `bitbucket` to `greenelab`;
- Bump the version number;
- Update `tribe-client` in PyPI.
- Create an issue in each repo that points to the bitbucket open issues URL (to remind us to digest them later).

**Comment by rzelayafavila** [comment]
Repositories have been migrated here, to GitHub, all of the tasks above have been completed, and the `.hgignore` files have been converted to `.gitignore` files, with their customary syntax.
