### ISSUE TITLE
"High weight genes" vs. "High-weight genes"

### ISSUE THREAD

**Issue by gwaygenomics** [greenelab/adage-server#220]
In the `Signature Information` page in the drop down menu just under

> Each signature is comprised of genes with varying importance. Different methods can be used to find the most relevant set of genes. Filter genes in this signature using: 

There are two options: **"High weight genes"** and **"High-weight genes"**. Only **"High weight genes"** actually selects genes. [Example here maybe](http://adage.greenelab.com/#/signature/400)

Not sure if this is already known - did a quick search in the issues but couldn't find a reference.

**Comment by dongbohu** [comment]
This issue seems to be because both `High weight genes` and `High-weight genes` were added in `ParticipationType` table in the database, but only the former is being used. 

@rzelayafavila and @mhuyck: In the last deployment (v0.8.1b), was `ParticipationType` table created from scratch or was updated from the previous version?

**Comment by mhuyck** [comment]
Everything was created from scratch (including the database) using the `fabfile` scripts.

**Comment by mhuyck** [comment]
It appears that the label with a space (`High weight genes`) that has data behind it comes from `adage_server.py`, line 196, as expected.

The only place I see the label with a hyphen (`High-weight genes`) in the codebase is in `migrations/0009_auto_20170503_1700.py`, line 17. That code must be getting run at migration time by line 35 of that same file.

**Comment by mhuyck** [comment]
Note that when we build from scratch, all migrations are run before any data get loaded, so this is to be expected, I guess.

**Comment by dongbohu** [comment]
@mhuyck: good catch! Since we are not using `high-weight genes`, which is created in `migrations/0009_auto_20170503_1700.py`), we can actually remove this migration file, right?

**Comment by mhuyck** [comment]
If this step was only necessary to migrate an existing DB with data then I would agree. It appears that file came along with a PR that @rzelayafavila did, so I'd like to have him confirm before we remove it.

**Comment by mhuyck** [comment]
Also: the next migration (`0010_auto_20170503_1714.py`) depends upon this one, so we can't just remove `0009...` but maybe we can if we also update line 11 of `0010...`.

**Comment by dongbohu** [comment]
Yes, I remember @rzelayafavila created this migration file manually to patch the existing database.

**Comment by rzelayafavila** [comment]
Yep - so this was to add a first ParticipationType to the database, not really to patch it. In fact, it only creates it if there are no ParticipationTypes in the database. I think what we should really do is have the fabfile command tie the Participation objects to *that* ParticipationType that got created.

**Comment by rzelayafavila** [comment]
I don't think we actually want to remove that migration.

**Comment by mhuyck** [comment]
That should say to remove lines 195-199 actually (not just line 196). We don't need the management command to `create_or_update_participation_type` in our fabfile, in other words.

**Comment by dongbohu** [comment]
I think what @mhuyck proposes makes sense.

**Comment by dongbohu** [comment]
After lines 195-199 are removed, I suggest that we add a comment line before line 200 to explain that the participation type `High-weight genes` has been created by **migrations/0009_auto_20170503_1700.py**.

**Comment by dongbohu** [comment]
We should also decide whether the participation type name should be called `High-weight genes` (with hyphen) or `High weight genes` (with space).

**Comment by mhuyck** [comment]
We already decided that the hyphen was desired, it appears: https://github.com/greenelab/adage-server/pull/140/commits/148fca27e9da9c847f32aac89d3c5d1ce88d89dc

**Comment by rzelayafavila** [comment]
Yep exactly @mhuyck and @dongbohu

**Comment by rzelayafavila** [comment]
Exactly, nice catch @mhuyck! I remember when we made this change, to use high-weight genes with a hyphen.

**Comment by dongbohu** [comment]
Great! I am going to submit a PR to fix this issue.

**Comment by rzelayafavila** [comment]
Thanks @dongbohu!
