### ISSUE TITLE
Figure out if we should make Postgres its own Docker container for purposes of development and other small, local (non-AWS or equivalent)- based instances, and implement it if so

### ISSUE THREAD

**Issue by rzelayafavila** [greenelab/adage-server#225]
This is a sub-issue of issue #193 

This came up in https://github.com/greenelab/adage-server/pull/221

**Comment by mhuyck** [comment]
I added a comment over at #221, but that's already closed so it really belongs here.

We definitely want to use a properly tuned, optimized and backed up server for our production DB, and we get that with RDS on AWS. At the same time, a Docker-based DB would fulfill two of the goals I think we should have:

> a developer (or independent lab) can pull our Docker image and get up and running with minimal configuration

Noted here: https://github.com/greenelab/adage-server/issues/193#issuecomment-313806195

**Comment by rzelayafavila** [comment]
I agree @mhuyck, it is what I was thinking as well. I think we've always wanted to use RDS or equivalent for production, and for the reasons you describe, having a Docker-based DB for developers and other researchers. I think I should've made the title of this issue more specific to address this - I will change it.

**Comment by rzelayafavila** [comment]
Resolved via https://github.com/greenelab/adage-server/pull/247
