### ISSUE TITLE
bitbucket: searching on kinB produces results, but not kinb (see also rpoN/rpon)

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#231]
Bitbucket issue `#8`: (priority: major)
https://bitbucket.org/greenelab/adage-server/issues/8/searching-on-kinb-produces-results-but-not

This is likely a tokenizer setting. Our current setup breaks `kinB` into `kin` and `B`, but not `kinb`. I think I remember seeing a tokenizer that could help preserve the original word-boundary tokens and this "CamelCase" tokenization. Need to make some adjustments in the Elasticsearch settings.

**Comment by rzelayafavila** [comment]
Hmmm - did we tackle this already @mhuyck? It seems to me that we did, in one of our search upgrades.

**Comment by mhuyck** [comment]
I think so... we even have tests now. Let me double-check.

**Comment by rzelayafavila** [comment]
I think this is the PR that you made that I am thinking about: https://github.com/greenelab/adage-server/pull/181

**Comment by mhuyck** [comment]
Yes. This is a dup for #123, and it has been fixed. I just double-checked by testing with the cases noted and cannot reproduce.
