### ISSUE TITLE
bitbucket: searches for cbrA and cbr produce the same results ("a" is a stop word)

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#232]
Bitbucket issue `#9`: (priority: minor)
https://bitbucket.org/greenelab/adage-server/issues/9/searches-for-cbra-and-cbr-produce-the-same

This may be the same cause as the previous bug, but tracking it separately in case it's not.

**Comment by mhuyck** [comment]
Dup for #123. Confirmed that I cannot reproduce this issue on the current release (v0.8.1).
