### ISSUE TITLE
bitbucket: why don't all 16 samples from E-GEOD-33245 appear in search results when searching for cbrA?

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#233]
Bitbucket issue `#10`: (priority: minor)
https://bitbucket.org/greenelab/adage-server/issues/10/why-dont-all-16-samples-from-e-geod-33245

Need to investigate why this and similar search results don't produce quite what I would expect.

**Comment by mhuyck** [comment]
This one is still a bug as of v0.8.1b. Probably an issue with the way indexes are built. Needs further investigation.

**Comment by mhuyck** [comment]
Tested again after merging #251, and the re-indexing done for that issue has resolved this one as well.
