### ISSUE TITLE
bitbucket: make routing work for Sample and Experiment

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#236]
Bitbucket issue `#14` (priority: minor)
https://bitbucket.org/greenelab/adage-server/issues/14/make-routing-work-for-sample-and

See http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-sref for relevant ui-router example. The core refactoring (hard part) has been done to support this now, but I need to think a little about how the routes for the whole site should come together before working them in.

**Comment by mhuyck** [comment]
This is really another way of stating #63. Dup.
