### ISSUE TITLE
bitbucket: Remove json format options from tests.py

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#237]
Bitbucket issue `#17` (priority: minor)
https://bitbucket.org/greenelab/adage-server/issues/17/remove-json-format-options-from-testspy

According to tastypie's source code:
https://github.com/django-tastypie/django-tastypie/blob/master/tastypie/test.py

The default `format` parameter in all api_client's methods (*get/put/post/patch/delete*) is `json`, so in `analyze/tests.py`, the options of `format=json` in a URI and `data={'format': 'json'}` in api_client's method calls are redundant. We can safely remove them and make the code cleaner and easier to maintain.

**Comment by dongbohu** [comment]
I am pretty sure this issue has been fixed by @mhuyck in one of his PRs a few months ago.

**Comment by mhuyck** [comment]
True. Actually, I think this was a team effort... I just pointed out instances where I found this issue. At any rate, I don't see any current tests with the `format` parameter anymore.
