### ISSUE TITLE
bitbucket: update package.json with correct license_url

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#243]
Bitbucket issue `#22` (priority: trivial)
https://bitbucket.org/greenelab/adage-server/issues/22/update-packagejson-with-correct

The license_url location will change once we migrate the source to GitHub.

**Comment by dongbohu** [comment]
Right now the `licence_url` field points to:
```
https://raw.github.com/ngbp/ngbp/master/LICENSE
```
I think we can safely close this issue. What do you think @mhuyck?

**Comment by mhuyck** [comment]
Oh, wait. I didn't read far enough. Looks like we DID fix the license. So we do just need to update the `license_url` to point to our repo, right?

**Comment by dongbohu** [comment]
Good point. I forgot that we have our own license file in the repo.

**Comment by dongbohu** [comment]
I am going to file another PR to fix this one too.
