### ISSUE TITLE
Reviewer Request - clear analysis basket

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#248]
Item from manuscript review:

"It would be convenient to add feature to clear analysis basket; samples remain in the basket unless they are individually removed or browser is refreshed."

We have a hard deadline on this - I think the feature is very fast to implement, but FYI:
"A decision will be made once we have received your revised manuscript, which we expect by 28 Sep 2017."

This timeline probably means that we need an implemented version ~2 weeks before that @mhuyck / @dongbohu

**Comment by mhuyck** [comment]
This is a good idea and, yes, it should be trivial to implement. I'll have a quick look at this today.

**Comment by dongbohu** [comment]
@mhuyck: Thanks. Please let me know if you need any help.
