### ISSUE TITLE
Export gene list from Gene Network view

### ISSUE THREAD

**Issue by mhuyck** [greenelab/adage-server#273]
It would be nice to have a way to export a list of the genes currently showing in the Gene Network view.

(Request from Hogan lab via @cgreene)

**Comment by cgreene** [comment]
Solving #347 also solves this (users could just take the first column of the CSV). I suggest focusing solely on #347 and closing this one. @mhuyck what do you think?

**Comment by mhuyck** [comment]
Exactly. Issue #347 is a slightly more detailed version of this, so solving that will automatically "fix" this -- unless it would be cumbersome to strip out that extra information.

Hm... actually, looking back at #347, that issue is asking for a list of *edges*, so simply taking one column might not get a complete list of the genes. To guarantee that, a user would need to concatenate the `Gene1` and `Gene2` columns and then remove the duplicates to get the list requested here. That's a simple matter of programming, but maybe not trivial for a user.

Aside: many of the "network file formats" supported by Cytoscape (issue #261) incorporate separate sections for a list of nodes (`Gene`s, in our case) and edges. This seems redundant, but if you have nodes that do not connect with any others, your network would be incomplete if it specified only edges. I think we just need to supply *both* a list of genes *and* a list of edges, for completeness.

**Comment by cgreene** [comment]
I propose a download menu that, when clicked, reveals three options: `Genes`, `Network (CSV)`, and `Cytoscape`.

**Comment by mhuyck** [comment]
I'm now envisioning the solution to all three issues (#261, #273, and #347) is an alternate "view" for the gene network that simply tabulates the genes and edges, along with a button for downloading in various formats.

**Comment by mhuyck** [comment]
A menu could work, too. That would allow downloading each format as @cgreene describes, but it would lack the tabular "preview".

**Comment by cgreene** [comment]
If the tabular preview is even more than a minuscule amount of work, I'd suggest doing download only.

**Comment by mhuyck** [comment]
I will delve into the code and that should tell me which path would be simpler: integrating new menu items or providing a separate view. I expect the work would be about the same.

**Comment by mhuyck** [comment]
This was straightforward to implement with the menu approach suggested by @cgreene. (The "view" approach I had in mind would have required a substantial refactor to better separate model from view code.)

I will be filing a WIP PR on this soon (along with a demo site) to ask questions about a couple of details.
