### ISSUE TITLE
Description of model, when selected

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#275]
When the user chooses a model on the homepage, can we provide a description of it?

> On the home page or About page, what do you think about adding text like: 
> Referencing ADAGE: 
> The eADAGE model is described in XXXX. Support for the development of this tool came from the Gordon and Betty Moore Foundation (PI, Casey Greene) and the Cystic Fibrosis Foundation (Greene and Hogan, PIs). 
> For an r package that enables the analysis of unpublished datasets not yet incorporated in the model, please refer to XXXX.

The text for eADAGE would be:

>The eADAGE model is described in [Tan et al., 2017. _Cell Systems_](www.cell.com/cell-systems/abstract/S2405-4712(17)30231-4). The development of this model was supported by GBMF 4552 from the Gordon and Betty Moore Foundation (PI, Casey Greene) and the Cystic Fibrosis Foundation STANTO15R0 (Greene and Hogan, PIs). 
> 
> An R package that can be used to analyze datasets that have not yet been shared is available and has been described in [Tan et al., 2017. _bioRxiv_](biorxiv.org/content/early/2017/06/27/156620).

**Comment by cgreene** [comment]
This could be a small text blurb below the model selection field instead of a tooltip if it's easier.

**Comment by dongbohu** [comment]
Fixed in PR #340.
