### ISSUE TITLE
Signature ordering / node numbers

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#276]
The signatures are ordered alphabetically. Deb suggests ordering in a more natural numeric order. We should strongly consider reprocessing our model to zero-pad those with fewer than three digits. This way the orders will be the same.

We should also add a note to the documentation somewhere to recommend this step before adding models.

**Comment by dongbohu** [comment]
My fault. I forgot to add this issue during the weekend.

**Comment by cgreene** [comment]
@dongbohu : No worries! :smile: I was posting a different issue this morning and remembered. No need to add during the weekend!

**Comment by cgreene** [comment]
Deepa added:
> I agree with @dhogan's suggestion to order it numerically. It's odd to find node13 after node138. We can also add column headers Node Pos or Node Neg and list just the numbers if that kind of representation fits into the domain language. Also, if pos and neg are short for Positive and Negative, it would be best to expand them in the column headers.

I have some additional thoughts:
> I wonder if this is an issue we want to solve at the model input level, as opposed to the webserver level. I think we might be able to instruct those who set up server instances and load models on how to name their attributes in the documentation. It feels more like an issue at that layer than the display layer.

**Comment by dongbohu** [comment]
@cgreene: You mean in the documentation, telling the user who sets up the web server that the signature names are ordered alphabetically. If they want to see them in a certain order, they may need to pad the signature names (such as changing `sig1` into `sig001`)?

I agree that this is more related to the backend than it is to the web UI, because we can not assume that signature names will be always in a certain structured string format.

**Comment by cgreene** [comment]
@dongbohu : Yes - telling the user who sets up the web server that signature names will be ordered alphabetically and that ordering should be meaningful. There is some interest in loading other types of models into these servers as well, and as you note their signature names could come in any form (i.e., assuming a certain structure would be troublesome).

**Comment by dongbohu** [comment]
Fixed in PR #281.
