### ISSUE TITLE
"+ Add" button should not leave the search results page

### ISSUE THREAD

**Issue by mhuyck** [greenelab/adage-server#284]
Reported by @jaclyn-taroni in #142:

> if I add all samples from an experiment with the +Add button, I am still taken to the experimental detail page.

**Comment by mhuyck** [comment]
It appears that the mouse click is getting grabbed by both the button and the table cell, so we need to make a tweak somewhere to stop the mouse click from propagating after the button gets it.

**Comment by cgreene** [comment]
Is this the same as #319?

**Comment by mhuyck** [comment]
Yes... looks as if #319 is a dup for this one.
