### ISSUE TITLE
mlmodel should be selectable

### ISSUE THREAD

**Issue by cgreene** [greenelab/adage-server#29]
Potential designs: something like choosing a tissue in GIANT ( http://giant.princeton.edu/ ) but only allowing a single selection at this time.

**Comment by dongbohu** [comment]
According to discussions with Casey and Rene, this **mlmodel selector** widget will be added to both **gene search** and **gene network** web UIs.

**Comment by rzelayafavila** [comment]
Resolved as of Pull Request #68
