### ISSUE TITLE
Bundle d3.network.js into release

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#294]
The best way to include `d3.network.js` seems to create a repo that includes our own version of `d3.network.js`, then developers in Greene Lab will fork it for code reviews. Then include the greenelab version in `interface/package.json`:
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by mhuyck** [comment]
I like this plan, and it goes a step beyond what I was thinking by figuring out how to incorporate from that repo via our existing `npm` build step... The part I had thought about (which is maybe what @dongbohu means) is:

1. create a fork of `d3.network.js` from [Aaron Wong's repository](https://github.com/aaronkw/d3-network) *using the GreeneLab GitHub account*.
2. GreeneLab developers contributing to this repo can fork from the GreeneLab fork and we can perform our code reviews and PRs as usual
3. any of the GreeneLab changes that might be useful can be offered back to the "upstream" repository via normal pull requests as well (but this should follow whatever procedure Aaron wants to use)

I guess this is pretty much the obvious approach to take.

We should also discuss (as a group ourselves *and* with @aaronkw) which GreeneLab coding standards ought to be applied as part of our code reviews on this file. My initial thought is that we should follow the parts of our protocol aimed at ensuring extra eyes see the code before it's committed to the GreeneLab repo, but we should probably preserve the coding style of the original project. But that should obviously be a discussion.

**Comment by rzelayafavila** [comment]
@dongbohu and @mhuyck: that makes sense - that is what I was thinking as well.

**Comment by aaronkw** [comment]
BTW, I’m not going to maintain or add features to the project since it’s a bit outdated, and we'd like to migrate to d3 4.0 soon. Feel free to maintain it if you'd like!

**Comment by dongbohu** [comment]
Thanks @aaronkw for the update!
