### ISSUE TITLE
Navigating away from page http://adage.greenelab.com/#/signature/9 takes too long in Firefox.

### ISSUE THREAD

**Issue by rzelayafavila** [greenelab/adage-server#299]
For some reason, this is not an issue in Chrome.

To replicate this error, navigate to http://adage.greenelab.com/#/signature/9 in Firefox and then try to click on one of the other tabs, like `Download`, `Analyze` or `Gene Network`. If you give it enough time to load, it will eventually get there.

**Comment by rzelayafavila** [comment]
This is also an issue in Firefox for the following Signature page, http://adage.greenelab.com/#/signature/304 (and probably other Signature pages that are heavy for the browser to process as well).

**Comment by mhuyck** [comment]
I got the same behavior testing on my Mac Firefox as well just now. I got this error as well:

![screen shot 2017-11-13 at 1 56 10 pm](https://user-images.githubusercontent.com/1151166/32743566-c5882de4-c87a-11e7-9844-4d9a086bb362.png)

Clicking on the "Debug script" button yields this:

![screen shot 2017-11-13 at 1 56 38 pm](https://user-images.githubusercontent.com/1151166/32743610-e48212fa-c87a-11e7-9b5c-c60379fa5e06.png)

I did not attempt to debug our minified JavaScript... this is a potentially helpful lead, though. If we test with a debug build it might become obvious what code Firefox is tripping over.

**Comment by mhuyck** [comment]
This issue sounded vaguely familiar, so I looked. I believe this problem is a dup for: https://github.com/greenelab/adage-server/issues/52

**Comment by dongbohu** [comment]
This seems to be fixed in Firefox Quantum (57.0).

**Comment by mhuyck** [comment]
Confirmed that this no longer happens in Firefox 60.0.2 on Mac.
