### ISSUE TITLE
Warning of Node page on Firefox: Unresponsive script 

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#52]
The **Experiment with highest range** section on the **Node** page is using a vega-lite widget to show activity values of all related samples. Here is an example:
http://165.123.67.202/#/node/10998

The loading speed of this widget seems reasonable on Chrome and Chromium, but on Firefox version 50.1.0, it took much longer time, and although the vega-lite widgets eventually showed up, we got this warning message:
```
A script on this page may be busy, or it may have stopped responding. 
You can stop the script now, open the script in the debugger, or let the script continue.
```

If the following line in `interface/src/app/node/node.js` is commented out:
```
vg.embed('#exp-' + i, embedSpec, function(error, result) { });
```
then the issue would be gone (but the vega-lite widget would disappear too).

No solution found yet. Need to test other web browsers and other versions of Firefox too.

**Comment by dongbohu** [comment]
Tested the Same page on Safari 10.0.1 on Mac OS X Sierra and IE 11 on Windows 7. Neither had this issue.

**Comment by mhuyck** [comment]
As noted in #299, this can no longer be reproduced in current versions of Firefox.
