### ISSUE TITLE
Correlation filter in the gene network page

### ISSUE THREAD

**Issue by tj8901nm** [greenelab/adage-server#67]
As Deb and I were going through the network page, we found that the correlation filter bar on the top of the page can only go one way. It would be great to have another filter going oppositely so that only genes with negative correlations higher than a cutoff are shown.

**Comment by dongbohu** [comment]
@tj8901nm: Are you saying that you need a filter that is able to set both the min and maximum value of the edge weight? Like the **Range slider** on this page:
http://angular-slider.github.io/angularjs-slider

**Comment by tj8901nm** [comment]
@dongbohu Yes, exactly what I want
