### ISSUE TITLE
search autocomplete on Gene Network page should not show genes already selected

### ISSUE THREAD

**Issue by mhuyck** [greenelab/adage-server#69]
Steps to reproduce:

1. go to Gene Network page (`/gene_search`)
2. select a machine learning model
3. search for a partial gene name with many matches (e.g. "dna")
4. select a gene from the list of hits (e.g. "dnaQ")
5. search for the same partial gene name again (e.g. "dna")

At this point, "dnaQ" still appears to be selectable. Attempts to select it from the list will be ignored, which is good, but it would be better if the list of choices were already filtered so "dnaQ" does not appear since it doesn't make sense to select it again.

**Comment by rzelayafavila** [comment]
Resolved with merging of PR #196
