### ISSUE TITLE
Gene Network view needs a "home" in the nav bar

### ISSUE THREAD

**Issue by mhuyck** [greenelab/adage-server#71]
Searching on a gene in "GeneNetwork" and clicking the "View Genes as Network" button produces a page (`gene_network`) with none of the nav bar elements selected. This should not happen. Every view on the site should have a "home" so the user can develop a "sense of place" about where things live on the site. In this case, the "GeneNetwork" tab should probably stay highlighted.

One way to help address this would be to keep a small representation of what was selected on the main entry (`gene_search`) view drawn at the top of the `gene_network` page. This should take up very little room to allow free exploration of the network using as much of the window as possible, but it would also be helpful to retain a bit of the context of what is being viewed here. Some web sites have implemented this as "breadcrumbs," a feature which is available in Bootstrap, but it's not clear that's exactly the right approach here -- I mention it mainly to explain what I'm thinking. The implementation details should be spearheaded by whomever decides to tackle this issue.

**Comment by dongbohu** [comment]
Fixed in PR #116.
