### ISSUE TITLE
Several URLs need to include a parameter for MLModel

### ISSUE THREAD

**Issue by mhuyck** [greenelab/adage-server#72]
To accommodate MLModel selectability (PR #68) several existing front end URLs (`ui.router` states) and possibly back end APIs (`urls.py`) need to be extended to include an MLModel parameter. This issue exists to track those areas as they are discovered.

**Comment by mhuyck** [comment]
`gene_network`

**Comment by rzelayafavila** [comment]
So far, this issue has been resolved, as the gene_network url includes a parameter for MLModel. If we find that we need to include the parameter in other URLs, we can open up another issue.
