### ISSUE TITLE
New constant service: activityDigits

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#82]
This constant will be the number of digits after the decimal point in activity values. So far it will be used in the following places:

* `high range experiment` section of node page

* sample annotations module (when node parameter is in the URL, activity values will be shown in the table.

**Comment by mhuyck** [comment]
I like this plan and will use a similar strategy for t-test p-value formatting. For reference, this came up during discussion of pull request #77.

**Comment by dongbohu** [comment]
Fixed in PR #86.
