### ISSUE TITLE
Home page content

### ISSUE THREAD

**Issue by rzelayafavila** [greenelab/adage-server#90]
What content needs to go in the home page (at the '/#/home' url)? @tj8901nm mentioned that it could be something similar to the README here: https://github.com/greenelab/ADAGEpath .

**Comment by mhuyck** [comment]
I've been tuning this out during my testing so have become blind to it, but the lack of text on the home page was noted during the brief review of the site that @cgreene and I did with Deb last Friday. We should make sure to finish this before publishing a paper that refers to the web site.
