### ISSUE TITLE
Volcano plot needs multiple testing correction

### ISSUE THREAD

**Issue by mhuyck** [greenelab/adage-server#96]
In today's discussion with @tj8901nm, it became clear that we need to be performing multiple testing correction on the p-values produced by the t-tests. (There's one t-test per node and we have 600 nodes, so we definitely have multiple testing!)

**Comment by mhuyck** [comment]
This package might prove helpful: https://www.npmjs.com/package/multtest

Have not done a thorough search yet.

**Comment by rzelayafavila** [comment]
Update: We are now using the ``multtest`` package @mhuyck mentioned above for FDR correction. It has been browserified and is ready to use anywhere in our code. It is available via the MathFuncts factory in the greenelab.stats module.

**Comment by rzelayafavila** [comment]
Closed as of PR #108
